### ISSUE TITLE
boot-plus-generator:1.2.0:generate 报错

### ISSUE THREAD

**Issue by yirenkeji555** [zhouxx/boot-plus#3]
![image](https://user-images.githubusercontent.com/48214423/143814094-6d9a0aca-15a8-467c-b9c4-0103c02850ab.png)

[INFO] --- boot-plus-generator:1.2.0:generate (default-cli) @ boot-plus-mybatis-jpa-samples ---
Mon Nov 29 13:27:35 CST 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
/com/alilitech/domain/Comment.java:3: 错误: 程序包javax.persistence不存在
import javax.persistence.Table;
                        ^
/com/alilitech/domain/Comment.java:5: 错误: 找不到符号
@Table(name = "jd_comment")
 ^
  符号: 类 Table
2 个错误
java.lang.ClassNotFoundException: com.alilitech.domain.Comment
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at com.alilitech.generate.DynamicLoader$MemoryClassLoader.findClass(DynamicLoader.java:122)
	at com.alilitech.generate.GeneratorUtils.loadClass(GeneratorUtils.java:273)
	at com.alilitech.generate.GeneratorUtils.lambda$process$0(GeneratorUtils.java:154)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alilitech.generate.GeneratorUtils.process(GeneratorUtils.java:147)
	at com.alilitech.generate.GeneratorMojo.execute(GeneratorMojo.java:82)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by yirenkeji555** [comment]
使用的demo是 https://github.com/zhouxx/boot-plus-mybatis-jpa-samples

**Comment by zhouxx** [comment]
你是通过generator这个去连接数据库表生成相关的实体类和mapper的吗

**Comment by Diluka** [comment]
@zhouxx 

```pom.xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
    http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>boot-plus-demo</artifactId>

    <version>1.0</version>

    <build>
        <plugins>
            <plugin>
                <groupId>com.alilitech</groupId>
                <artifactId>boot-plus-generator</artifactId>
                <version>1.3.9</version>
                <dependencies>
                    <dependency>
                        <groupId>com.alilitech</groupId>
                        <artifactId>boot-plus-mybatis-jpa</artifactId>
                        <version>1.3.9</version>
                    </dependency>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>8.0.19</version>
                        <scope>runtime</scope>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
```

```generate.xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <datasource>
        <url>jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&amp;useSSL=false</url>
        <driverName>com.mysql.cj.jdbc.Driver</driverName>
        <username>root</username>
        <password>root</password>
    </datasource>

    <properties>
        <projectPath>src/main/java</projectPath>
        <packageName>demo</packageName>
    </properties>

    <tables>
        <table tableName="author" />
        <table tableName="book" />
    </tables>
</config>
```


```log
/demo/domain/Author.java:3: 错误: 程序包com.alilitech.mybatis.jpa.anotation不存在
import com.alilitech.mybatis.jpa.anotation.GeneratedValue;
                                          ^
/demo/domain/Author.java:4: 错误: 程序包com.alilitech.mybatis.jpa.parameter不存在
import com.alilitech.mybatis.jpa.parameter.GenerationType;
                                          ^
/demo/domain/Author.java:6: 错误: 程序包javax.persistence不存在
import javax.persistence.Id;
                        ^
/demo/domain/Author.java:7: 错误: 程序包javax.persistence不存在
import javax.persistence.Table;
                        ^
/demo/domain/Author.java:9: 错误: 找不到符号
@Table(name = "author")
 ^
  符号: 类 Table
/demo/domain/Author.java:12: 错误: 找不到符号
	@Id
	 ^
  符号:   类 Id
  位置: 类 Author
/demo/domain/Author.java:13: 错误: 找不到符号
	@GeneratedValue(value = GenerationType.AUTO)
	 ^
  符号:   类 GeneratedValue
  位置: 类 Author
/demo/domain/Author.java:13: 错误: 找不到符号
	@GeneratedValue(value = GenerationType.AUTO)
	                        ^
  符号:   变量 GenerationType
  位置: 类 Author
8 个错误
java.lang.ClassNotFoundException: demo.domain.Author
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at com.alilitech.generate.DynamicLoader$MemoryClassLoader.findClass(DynamicLoader.java:122)
	at com.alilitech.generate.GeneratorUtils.loadClass(GeneratorUtils.java:223)
	at com.alilitech.generate.GeneratorUtils.lambda$process$0(GeneratorUtils.java:127)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.alilitech.generate.GeneratorUtils.process(GeneratorUtils.java:122)
	at com.alilitech.generate.GeneratorMojo.execute(GeneratorMojo.java:81)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```


```sql
create table author
(
	id varchar(36) not null
		primary key,
	created_at datetime(6) null,
	updated_at datetime(6) null,
	version bigint null,
	birthday date null,
	name varchar(255) null
);

create table book
(
	id varchar(36) not null
		primary key,
	created_at datetime(6) null,
	updated_at datetime(6) null,
	version bigint null,
	author_id varchar(36) not null,
	name varchar(255) null,
	tags json null,
	constraint FKklnrv3weler2ftkweewlky958
		foreign key (author_id) references author (id)
);
```

**Comment by zhouxx** [comment]
@Diluka  你更新下samples，我试了没有问题。如果方便的话可以远程，可以发到我邮箱 mozu_2008@163.com

**Comment by Diluka** [comment]
> @Diluka 你更新下samples，我试了没有问题。如果方便的话可以远程，可以发到我邮箱 [mozu_2008@163.com](mailto:mozu_2008@163.com)

https://github.com/zhouxx/boot-plus-mybatis-jpa-samples

generate.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <datasource>
        <url>jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&amp;useSSL=false</url>
        <driverName>com.mysql.jdbc.Driver</driverName>
        <username>root</username>
        <password>root</password>
    </datasource>

    <properties>
        <projectPath>src/main/java</projectPath>
        <packageName>demo</packageName>
    </properties>

    <tables>
        <table tableName="t_dept" />
        <table tableName="t_role" />
        <table tableName="t_user" />
    </tables>
</config>

```

```log
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
/demo/domain/TDept.java:3: 错误: 程序包com.alilitech.mybatis.jpa.anotation不存在
import com.alilitech.mybatis.jpa.anotation.GeneratedValue;
                                          ^
/demo/domain/TDept.java:4: 错误: 程序包com.alilitech.mybatis.jpa.parameter不存在
import com.alilitech.mybatis.jpa.parameter.GenerationType;
                                          ^
/demo/domain/TDept.java:5: 错误: 程序包javax.persistence不存在
import javax.persistence.Id;
                        ^
/demo/domain/TDept.java:6: 错误: 程序包javax.persistence不存在
import javax.persistence.Table;
                        ^
/demo/domain/TDept.java:8: 错误: 找不到符号
@Table(name = "t_dept")
 ^
  符号: 类 Table
/demo/domain/TDept.java:11: 错误: 找不到符号
	@Id
	 ^
  符号:   类 Id
  位置: 类 TDept
/demo/domain/TDept.java:12: 错误: 找不到符号
	@GeneratedValue(value = GenerationType.AUTO)
	 ^
  符号:   类 GeneratedValue
  位置: 类 TDept
/demo/domain/TDept.java:12: 错误: 找不到符号
	@GeneratedValue(value = GenerationType.AUTO)
	                        ^
  符号:   变量 GenerationType
  位置: 类 TDept
8 个错误
java.lang.ClassNotFoundException: demo.domain.TDept
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at com.alilitech.generate.DynamicLoader$MemoryClassLoader.findClass(DynamicLoader.java:122)
	at com.alilitech.generate.GeneratorUtils.loadClass(GeneratorUtils.java:223)
	at com.alilitech.generate.GeneratorUtils.lambda$process$0(GeneratorUtils.java:127)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.alilitech.generate.GeneratorUtils.process(GeneratorUtils.java:122)
	at com.alilitech.generate.GeneratorMojo.execute(GeneratorMojo.java:81)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

**Comment by zhouxx** [comment]
@Diluka 
猜一下，应该是动态编译的问题。需要确保JDK中的tools.jar在应用的 CLASSPATH中。可以在JDK里的配置里加上相关的包。

**Comment by Diluka** [comment]
@zhouxx 我执行的maven goal，如果配置有问题，那也是pom.xml上面配置不对，而且我和楼主都是遇到这种情况，完全可以猜测是你的环境和我们不一样，建议你在沙盒环境里面测试一下，比如maven的docker镜像里面

```sh
docker run --rm -it -v ~/.m2:/root/.m2 -v $(pwd):/app --workdir /app --network container:dev-mysql-1 maven bash -l

mvn boot-plus-generator:generate
```

**Comment by zhouxx** [comment]
@Diluka   设置classpath无效导致的，换了一种方式去设置classpath了，兼容了不同平台。此issue会在下个发布版本修复。

**Comment by zhouxx** [comment]
版本已发布。
